"""recreate books table

Revision ID: 02df56eb99b9
Revises: 4f334d5dea8e
Create Date: 2026-01-13 19:39:12.473269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02df56eb99b9'
down_revision: Union[str, Sequence[str], None] = '4f334d5dea8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('is_digital', sa.Boolean(), nullable=True),
    sa.Column('cover_image_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('is_restricted', sa.Boolean(), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('book_number', sa.String(length=100), nullable=True),
    sa.Column('parts_or_volumes', sa.String(length=100), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('subject_number', sa.String(length=100), nullable=True),
    sa.Column('translator', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('date_of_purchase', sa.Date(), nullable=True),
    sa.Column('edition', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.LanguageID'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_books_book_number'), 'books', ['book_number'], unique=False)
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    op.create_index(op.f('ix_books_serial_number'), 'books', ['serial_number'], unique=False)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_foreign_key(None, 'book_copies', 'books', ['BookID'], ['id'])
    op.create_foreign_key(None, 'book_permissions', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'book_subcategory_link', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'digital_access', 'books', ['BookID'], ['id'])
    op.create_foreign_key(None, 'upload_requests', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upload_requests', type_='foreignkey')
    op.drop_constraint(None, 'digital_access', type_='foreignkey')
    op.drop_constraint(None, 'book_subcategory_link', type_='foreignkey')
    op.drop_constraint(None, 'book_permissions', type_='foreignkey')
    op.drop_constraint(None, 'book_copies', type_='foreignkey')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_serial_number'), table_name='books')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index(op.f('ix_books_book_number'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###